In [1]:
import numpy as np 

arry2d = np.array([[5,4,5], [7,6,7], [9,6,4], [1,3,7]]) 
print(arry2d)

[[5 4 5]
 [7 6 7]
 [9 6 4]
 [1 3 7]]


In [2]:
import numpy as np 

arry3d = np.array([[[7,8,5], [4,5,7], [7,1,9], [5,8,10]],
                   [[2,1,2], [9,3,5], [3,7,6], [4,2,9]],
                   [[1,9,3], [4,4,8], [6,4,6], [8,1,3]]]) 
print(arry3d)

[[[ 7  8  5]
  [ 4  5  7]
  [ 7  1  9]
  [ 5  8 10]]

 [[ 2  1  2]
  [ 9  3  5]
  [ 3  7  6]
  [ 4  2  9]]

 [[ 1  9  3]
  [ 4  4  8]
  [ 6  4  6]
  [ 8  1  3]]]


In [6]:

arrygg = [[10,8,8,2], [9,2,2,2], [1,1,9,7], [14,4,6,8], [8,2,5,4]]

arryhasil = np.array(arrygg)
arryhasil[::2, :] += 1
arryhasil[:, 1::2] += 2

print(arryhasil)

[[11 11  9  5]
 [ 9  4  2  4]
 [ 2  4 10 10]
 [14  6  6 10]
 [ 9  5  6  7]]


In [7]:
arry3d = [[[7, 6, 5], [4, 7, 7], [7, 3, 9], [4, 4, 10]], 
          [[2, 6, 2], [9, 8, 5], [3, 6, 3], [6, 9, 9]], 
          [[2, 1, 3], [2, 4, 8], [1, 9, 6], [8, 3, 2]]]

arrybalik = np.array(arry3d)
arrybalik = np.flip(arrybalik, axis=2)
print(arrybalik)

[[[ 5  6  7]
  [ 7  7  4]
  [ 9  3  7]
  [10  4  4]]

 [[ 2  6  2]
  [ 5  8  9]
  [ 3  6  3]
  [ 9  9  6]]

 [[ 3  1  2]
  [ 8  4  2]
  [ 6  9  1]
  [ 2  3  8]]]


In [8]:
arry3d = [[[7, 6, 5], [4, 7, 7], [7, 3, 9], [4, 4, 10]], 
          [[2, 6, 2], [9, 8, 5], [3, 6, 3], [6, 9, 9]], 
          [[2, 1, 3], [2, 4, 8], [1, 9, 6], [8, 3, 2]]]

arry3d = np.array(arry3d)
arryreshape = arry3d.reshape(6,6)
print(arryreshape)



[[ 7  6  5  4  7  7]
 [ 7  3  9  4  4 10]
 [ 2  6  2  9  8  5]
 [ 3  6  3  6  9  9]
 [ 2  1  3  2  4  8]
 [ 1  9  6  8  3  2]]


In [5]:
arry = np.array([[6, 11, 10, 7],
                   [7, 5, 4, 10],
                   [9, 10, 2, 5],
                   [1, 3, 9, 2],
                   [6, 10, 5, 2],
                   [4, 5, 9, 4]])

kiri_atas = np.hsplit(np.vsplit(arry, 2)[0], 2)[0]
kiri_bawah = np.hsplit(np.vsplit(arry, 2)[1], 2)[0]
kanan_atas = np.hsplit(np.vsplit(arry, 2)[0], 2)[1]
kanan_bawah = np.hsplit(np.vsplit(arry, 2)[1], 2)[1]

a = np.vstack((kanan_bawah, kanan_atas))
b = np.vstack((kiri_bawah, kiri_atas))

finalarry = np.hstack((a, b))

print("Array Awal:")
print(arry)
print()
print("Array Setelah Diubah:")
print(finalarry)

Array Awal:
[[ 6 11 10  7]
 [ 7  5  4 10]
 [ 9 10  2  5]
 [ 1  3  9  2]
 [ 6 10  5  2]
 [ 4  5  9  4]]

Array Setelah Diubah:
[[ 9  2  1  3]
 [ 5  2  6 10]
 [ 9  4  4  5]
 [10  7  6 11]
 [ 4 10  7  5]
 [ 2  5  9 10]]
